export const AlertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
};
export const AuthConstants = {

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",

  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",

  UNSUBSCRIBE_REQUEST : "UNSUBSCRIBE_REQUEST",
  UNSUBSCRIBE_SUCCESS : "UNSUBSCRIBE_SUCCESS",
  UNSUBSCRIBE_FAILURE : "UNSUBSCRIBE_FAILURE",
};
export const ProfileConstants = {
  PROFILE_REQUEST: "PROFILE_REQUEST",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  PROFILE_FAILURE: "PROFILE_FAILURE",

  GETPROFILE_REQUEST: "GETPROFILE_REQUEST",
  GETPROFILE_SUCCESS: "GETPROFILE_SUCCESS",
  GETPROFILE_FAILURE: "GETPROFILE_FAILURE",
};
